# Generated by Django 5.1.6 on 2025-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rome",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("WAIT_STAFF", "WaitStaff"),
                    ("CHEF", "Chef"),
                ],
                default="WAIT_STAFF",
                max_length=20,
            ),
        ),
    ]
