# Generated by Django 5.1.6 on 2025-03-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
