# Generated by Django 5.1.6 on 2025-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0002_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Served", "Served"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
